[project]
name = "hetero"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.21",
    "numpy>=2.4.0",
    "ray>=2.53.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
